In [1]:
import plotly.express as px
import pandas as pd
import numpy as np

df=pd.read_csv('data/house-prices/df.csv')

In [9]:
df.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [14]:
info=df.dtypes
info

Unnamed: 0         int64
Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice        float64
Length: 82, dtype: object

In [38]:
null_df=(df.isna().sum()[df.isna().sum()>0]/len(df)*100).reset_index()
null_df.sort_values(by=0,ascending=False,inplace=True)
null_df.columns=['columns','Null values']
null_df

         columns  Null values
30        PoolQC    99.657417
32   MiscFeature    96.402878
2          Alley    93.216855
31         Fence    80.438506
6     MasVnrType    60.500171
34     SalePrice    49.982871
22   FireplaceQu    48.646797
1    LotFrontage    16.649538
29    GarageCond     5.447071
24   GarageYrBlt     5.447071
25  GarageFinish     5.447071
28    GarageQual     5.447071
23    GarageType     5.378554
10  BsmtExposure     2.809181
9       BsmtCond     2.809181
8       BsmtQual     2.774923
13  BsmtFinType2     2.740665
11  BsmtFinType1     2.706406
7     MasVnrArea     0.787941
0       MSZoning     0.137033
21    Functional     0.068517
19  BsmtHalfBath     0.068517
18  BsmtFullBath     0.068517
3      Utilities     0.068517
20   KitchenQual     0.034258
16   TotalBsmtSF     0.034258
15     BsmtUnfSF     0.034258
26    GarageCars     0.034258
27    GarageArea     0.034258
14    BsmtFinSF2     0.034258
12    BsmtFinSF1     0.034258
5    Exterior2nd     0.034258
4    Exterior1st     0.034258
33      SaleType     0.034258
17    Electrical     0.034258

In [42]:
list(df.select_dtypes('object').columns)

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']